GET http://localhost:4000/api/projects
###
POST http://localhost:4000/api/projects
Content-Type: application/json

{
  "title": "Project 1",
  "description": "proj 1"
}
###
PUT http://localhost:4000/api/projects/4
###
DELETE http://localhost:4000/api/projects/4
###
